In [1]:
import os
import pandas as pd
import json

In [2]:
folder = 'supervised_rf'
full_path = '/home/haitong/PycharmProjects/low_rank_learning/log/NoisyPendulum/supervised_rf'
dfs = []
for dir in os.listdir(full_path):
    try:
        exp_path = os.path.join(full_path, dir)
        args_path = os.path.join(exp_path, 'args.json')
        with open(args_path, 'r') as f:
            args_dict = json.load(f)
        args_dict['exp_name'] = dir
        dfs.append(pd.DataFrame(args_dict, index=[0]))
    except:
        pass
df = pd.concat(dfs, ignore_index=True)
df_filtered = df.loc[:, df.nunique() > 1]
df_filtered

,train_batch_size,sample,lr,feature_dim,hidden_dim,hidden_depth,logprob_regularization,integral_normalization,integral_normalization_weights,nce_lr,num_classes,exp_name
0,1024,uniform_theta,0.0003,1024,512,3,False,True,0.1,0.00003,3,2024-06-11-22-54-59
1,512,gaussian,0.0001,1024,512,2,True,False,1.0,0.00010,5,2024-05-31-11-30-48
2,512,gaussian,0.0001,1024,256,2,True,False,1.0,0.00010,5,2024-05-31-11-29-13
3,512,gaussian,0.0001,512,256,2,True,False,1.0,0.00010,5,2024-05-31-11-24-01

In [3]:
df.loc[:, df.nunique() == 1]

,device,train_batches,dynamics,sigma,sin_cos_obs,prob_labels,layer_normalization,preprocess,estimator,logprob_regularization_weights,sigmoid_output,nce_loss,noise_dist,learnable_w
0,cuda,10000,NoisyPendulum,4.0,False,conditional,True,none,supervised_rf,1.0,False,ranking,uniform,False
1,cuda,10000,NoisyPendulum,4.0,False,conditional,True,none,supervised_rf,1.0,False,ranking,uniform,NaN
2,cuda,10000,NoisyPendulum,4.0,False,conditional,True,none,supervised_rf,1.0,False,ranking,uniform,NaN
3,cuda,10000,NoisyPendulum,4.0,False,conditional,True,none,supervised_rf,1.0,False,ranking,uniform,NaN